### PR TITLE
Major refactoring

### PR DESCRIPTION
**Pull request by guilhermearaujo**
A lot of the code has been cleaned up, reorganized and simplified;
ACE depencencies have been upgraded to v1.2.6 and use minified files;
Toggling raw/pretty modes does not reload page;

### CODE REVIEW

**Comment by acrogenesis** [comment]
Great PR! Thanks @guilhermearaujo

**Comment by guilhermearaujo** [comment]
Great @acrogenesis! Would you mind building a new package and bumping the version in `update.plist` so anyone can get this update?

**Comment by acrogenesis** [comment]
I don't have the certificate anymore, since Apple made safari extensions only for Apple Developers. So I can't create a new package.

**Comment by acrogenesis** [comment]
I did update the Readme in how to install it manually.

**Pull request merged**
